"""Initial tables

Revision ID: 24e710b8b0fe
Revises: 
Create Date: 2025-08-28 20:15:45.453800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e710b8b0fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescue_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rescue_centers_id'), 'rescue_centers', ['id'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rescue_center_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rescue_center_id'], ['rescue_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_rescue_centers_id'), table_name='rescue_centers')
    op.drop_table('rescue_centers')
    # ### end Alembic commands ###
